[cohere]
api_key = "7D5Y30Vg7BYjfZk1huZ5AAZ58esXEr0jH2QpWFa8"

[qdrant]
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.WuQMH6J-KFSz0rEzjv-IGQExy2Au9C8jV82BbYKf7QY"
host = "https://b2e7691c-8588-485a-938b-cc899e360d62.us-east-1-0.aws.cloud.qdrant.io"

[server]
fileWatcherType = "none"
